import { CategoryPreviewResponse } from "../interfaces/product/response/categoryPreviewResponse";

export const Categories: CategoryPreviewResponse[] = [
    {
        id: 1,
        title: "Floreros",
        icon: "string",
        description: "Para poner tus envases",
        subCategories: null,
    },
    {
        id: 2,
        title: "Macetas",
        icon: "string",
        description: "Para poner tus plantas",
        subCategories: null,
    },
    {
        id: 3,
        title: "Jardineras",
        icon: "string",
        description: "Para poner tus plantas",
        subCategories: null,
    },
    {
        id: 4,
        title: "Muebles",
        icon: "string",
        description: "Para poner tus plantas",
        subCategories: null,
    },
    {
        id: 5,
        title: "Espejos",
        icon: "string",
        description: "Para poner tus plantas",
        subCategories: null,
    },
    {
        id: 6,
        title: "Lamparas",
        icon: "string",
        description: "Para poner tus plantas",
        subCategories: null,
    },
    {
        id: 7,
        title: "Accesorios",
        icon: "string",
        description: "Para poner tus plantas",
        subCategories: null,
    },
    {
        id: 8,
        title: "Mesas",
        icon: "string",
        description: "Para poner tus plantas",
        subCategories: null,
    },
    {
        id: 9,
        title: "Sillas",
        icon: "string",
        description: "Para poner tus plantas",
        subCategories: null,
    },
    {
        id: 10,
        title: "Bancos",
        icon: "string",
        description: "Para poner tus plantas",
        subCategories: null,
    },
    {
        id: 11,
        title: "Mecedoras",
        icon: "string",
        description: "Para poner tus plantas",
        subCategories: null,
    },
    {
        id: 12,
        title: "Columpios",
        icon: "string",
        description: "Para poner tus plantas",
        subCategories: null,
    },
    {
        id: 13,
        title: "Camastros",
        icon: "string",
        description: "Para poner tus plantas",
        subCategories: null,
    },
    {
        id: 14,
        title: "Sombrillas",
        icon: "string",
        description: "Para poner tus plantas",
        subCategories: null,
    },
]