import { ProductPreviewResponse } from '../interfaces/Product/Response/productPreviewResponse'; 

export const Products: ProductPreviewResponse[] = [
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-02",
        title: 'Product 2',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-03",
        title: 'Product 3',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-04",
        title: 'Product 4',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
    {
        code: "SDA-01",
        title: 'Product 1',
        price: 100,
        offerPrice: 100,
        discountSave: 100,
        images: 'nada aun',
        stock: 'In Stock',
        quantityAvaliable: 10,
        condition: 'New',
        averageRating: 4.3,
        totalReviews: 10,
        reviews: null,
        discount: null,
    },
];
